# ----------------------------------------------------------------------------
# STEP_REGISTER_MODULES: db / credits / fashion_studio
# ----------------------------------------------------------------------------
import sys, types
print("📦 STEP_REGISTER_MODULES: Registering backend modules...")

_mod_db = types.ModuleType('db')
sys.modules['db'] = _mod_db
exec(compile((
    'import contextlib\n'
    'import os\n'
    'import threading\n'
    'import psycopg2\n'
    'from psycopg2 import pool as _pgpool\n'
    "DATABASE_URL = os.environ.get(\'DATABASE_URL\')\n"
    '_pool = None\n'
    '_pool_lock = threading.Lock()\n'
    '_last_used = {}\n'
    '\n'
    'def _get_pool():\n'
    '    global _pool\n'
    '    if _pool is None:\n'
    '        with _pool_lock:\n'
    '            if _pool is None:\n'
    "                _pool = _pgpool.ThreadedConnectionPool(minconn=1, maxconn=24, dsn=DATABASE_URL, connect_timeout=10, options=\'-c statement_timeout=90000\')\n"
    '    return _pool\n'
    '_PING_AFTER_IDLE_S = 60\n'
    '\n'
    'def _mark_used(conn):\n'
    '    import time\n'
    '    if len(_last_used) > 64:\n'
    '        _last_used.clear()\n'
    '    _last_used[id(conn)] = time.time()\n'
    '\n'
    'def _checkout():\n'
    '    import time\n'
    '    p = _get_pool()\n'
    '    for attempt in (1, 2):\n'
    '        conn = p.getconn()\n'
    '        if time.time() - _last_used.get(id(conn), 0) < _PING_AFTER_IDLE_S:\n'
    '            return conn\n'
    '        try:\n'
    '            with conn.cursor() as cur:\n'
    "                cur.execute(\'SELECT 1\')\n"
    '            conn.rollback()\n'
    '            return conn\n'
    '        except Exception:\n'
    '            p.putconn(conn, close=True)\n'
    '            if attempt == 2:\n'
    '                raise\n'
    "    raise RuntimeError(\'unreachable\')\n"
    '\n'
    '@contextlib.contextmanager\n'
    'def connection():\n'
    '    import time\n'
    '    conn = _checkout()\n'
    '    try:\n'
    '        yield conn\n'
    '    except Exception:\n'
    '        try:\n'
    '            conn.rollback()\n'
    '        except Exception:\n'
    '            _get_pool().putconn(conn, close=True)\n'
    '            raise\n'
    '        _mark_used(conn)\n'
    '        _get_pool().putconn(conn)\n'
    '        raise\n'
    '    else:\n'
    '        _mark_used(conn)\n'
    '        _get_pool().putconn(conn)\n'
    '\n'
    'class _PooledBorrow:\n'
    '\n'
    '    def __init__(self, conn):\n'
    '        self._conn = conn\n'
    '        self._returned = False\n'
    '\n'
    '    def __getattr__(self, name):\n'
    '        return getattr(self._conn, name)\n'
    '\n'
    '    def close(self):\n'
    '        if self._returned:\n'
    '            return\n'
    '        self._returned = True\n'
    '        try:\n'
    '            self._conn.rollback()\n'
    '        except Exception:\n'
    '            _get_pool().putconn(self._conn, close=True)\n'
    '            return\n'
    '        import time\n'
    '        _mark_used(self._conn)\n'
    '        _get_pool().putconn(self._conn)\n'
    '\n'
    'def borrow():\n'
    '    return _PooledBorrow(_checkout())'
), 'backend/db.py', 'exec'), _mod_db.__dict__)
print("  ✅ db module registered")
